In [3]:
from sklearn import preprocessing
import numpy as np


# row - a individual sample 
# column - a trait
x = np.array([[0., -3.,  1.],
              [3.,  1.,  2.],
              [0.,  1., -1.]])
# [0,1] normalization
min_max_scaler = preprocessing.MinMaxScaler()
min_max_x = min_max_scaler.fit_transform(x)
print(min_max_x)

[[0.         0.         0.66666667]
 [1.         1.         1.        ]
 [0.         1.         0.        ]]


In [4]:
from sklearn import preprocessing
import numpy as np


x = np.array([[0., -3.,  1.],
              [3.,  1.,  2.],
              [0.,  1., -1.]])
scaled_x = preprocessing.scale(x)
print(scaled_x)

[[-0.70710678 -1.41421356  0.26726124]
 [ 1.41421356  0.70710678  1.06904497]
 [-0.70710678  0.70710678 -1.33630621]]


In [5]:
import numpy as np


x = np.array([[0., -3.,  1.],
              [3.,  1.,  2.],
              [0.,  1., -1.]])

j = np.ceil(np.log10(np.max(abs(x))))
scaled_x = x/(10**j)
print(scaled_x)

[[ 0.  -0.3  0.1]
 [ 0.3  0.1  0.2]
 [ 0.   0.1 -0.1]]
